### ISSUE TITLE
How

### ISSUE THREAD

**Issue by serobalino** [tsanak/vue-carousel#2]
How to install with **npm** and how to import and declare the componnete

**Comment by tsanak** [comment]
I just uploaded a Carousel.vue file to work as a Single File Component with vue-cli built projects.

Also the README was updated to include an example usage of Carousel.vue

Unfortunately the carousel is not in the npm registry, cause I do not think that it will add real value as a package. 

If you have any issue with following the guide in the README, please let me know.
