### ISSUE TITLE
binding images prop to a vuex prop 

### ISSUE THREAD

**Issue by nagwan** [tsanak/vue-carousel#4]
hi @tsanak, first of all, thank u very much for this helpful component 
I am trying to play around and everything works perfectly as long as the images array is a data property, but once I bind it to a vuex state property I got an error related to the currentImage index and I cannot figure it out 

any ideas

**Comment by tsanak** [comment]
Hi, could you please elaborate a little more? How did you try to bind the props to the store?
I am trying to recreate the issue you mention but I can't.

I have set up a test project for this, below is the code that is working without any issue.

**Helloword.vue**
```vue
<template>
  <div class="hello">
    <carousel
      :images="images"
    ></carousel>
  </div>
</template>

<script>
import Carousel from '@/components/Carousel';
export default {
  name: 'HelloWorld',
  components: {
    Carousel
  },
  data() {
    return {
      images: this.$store.state.images
    }
  },
}
</script>
```

**store.js**
```javascript
import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    images: [
        {
            id: '1',
            big: '/images/p1.jpeg',
            thumb: '/images/thumbs/p1.jpeg'
        },
        {
            id: '2',
            big: '/images/p2.jpeg',
            thumb: '/images/thumbs/p2.jpeg'
        },
        {
            id: '3',
            big: '/images/p3.jpeg',
            thumb: '/images/thumbs/p3.jpeg'
        },
        {
            id: '4',
            big: '/images/p4.jpeg',
            thumb: '/images/thumbs/p4.jpeg'
        }
    ],
  },
  mutations: { },
  actions: { }
})

```
If you can share some code that recreates the problem, it would be really helpful.

**Comment by nagwan** [comment]
aha, thank u, the problem was in the sequence of rendering 
i used v-if and it works fine
